/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment2;

import assignment2.ComputerLab;

public class App {
    public static void main(String[] args) {
        new ComputerLab();
    }
}
